In [8]:
import numpy as np
import math

In [85]:
n = 10 # number of trash
m = 5 # size of grid
mu = [3, 2] # center of trash pile
sig = [[0.1, 0], [0, 0.1]] # spread of pile
var = 0.1 # error in measurements
field = np.zeros((m,m))# array of trash pieces dispersed on field
visits = np.zeros((m,m))# array to track number of visits to each gridpoint
reward = np.zeros((m,m))# array of expected means of each gridpoint
T = 10 # number of time steps
delta = 0.2 # amount reward decreases per visit

# place trash in field
trash = np.random.multivariate_normal(mu, sig, n)
for i in range(n):
    x = int(trash[i][0])
    y = int(trash[i][1])
    field[x][y] += 1
    
print(field)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 3. 2. 0. 0.]
 [0. 2. 3. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [86]:
# intialize agent
for i in range(m):
    for j in range(m):
        visits[i][j] += 1
        measure = field[i][j]
        reward[i][j] = round(np.random.normal(measure, var),1)
print(visits)
print(reward)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[ 0.1  0.   0.  -0.   0.1]
 [ 0.1  0.   0.  -0.1 -0.3]
 [ 0.1  3.   2.1  0.1  0. ]
 [ 0.1  1.8  3.  -0.   0. ]
 [-0.3  0.2 -0.   0.   0.1]]


In [87]:
# for T time steps choose an arm to visit and get a reward
for i in range (1,T+1):
    print("Time step: ", i)
    expected_mean = np.divide(reward, visits)
    Q = expected_mean + np.divide(math.sqrt(2*math.log(i)),np.sqrt(visits))
    ind = np.unravel_index(np.argmax(Q), Q.shape)
    measure = round(np.random.normal(field[ind], var),1)
    reward[ind] += measure*(1-delta**visits[ind])
    visits[ind] += 1
    print(Q)
    print(ind)
    print(visits)

Time step:  1
[[ 0.1  0.   0.   0.   0.1]
 [ 0.1  0.   0.  -0.1 -0.3]
 [ 0.1  3.   2.1  0.1  0. ]
 [ 0.1  1.8  3.   0.   0. ]
 [-0.3  0.2  0.   0.   0.1]]
(2, 1)
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 2. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Time step:  2
[[1.27741002 1.17741002 1.17741002 1.17741002 1.27741002]
 [1.27741002 1.17741002 1.17741002 1.07741002 0.87741002]
 [1.27741002 3.57255461 3.27741002 1.27741002 1.17741002]
 [1.27741002 2.97741002 4.17741002 1.17741002 1.17741002]
 [0.87741002 1.37741002 1.17741002 1.17741002 1.27741002]]
(3, 2)
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 2. 1. 1. 1.]
 [1. 1. 2. 1. 1.]
 [1. 1. 1. 1. 1.]]
Time step:  3
[[1.58230381 1.48230381 1.48230381 1.48230381 1.58230381]
 [1.58230381 1.48230381 1.48230381 1.38230381 1.18230381]
 [1.58230381 3.78814707 3.58230381 1.58230381 1.48230381]
 [1.58230381 3.28230381 3.78814707 1.48230381 1.48230381]
 [1.18230381 1.68230381 1.48230381 1.48230381 1.58230381]]
(2, 1)
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 

In [88]:
visits -= 1
print(visits)
print(field - visits)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 4. 1. 0. 0.]
 [0. 1. 4. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0. -1.  1.  0.  0.]
 [ 0.  1. -1.  0.  0.]
 [ 0.  0.  0.  0.  0.]]
