In [2]:
import numpy as np
import math

In [39]:
n = 100 # number of trash
m = 5 # size of grid
mu = [3, 2] # center of trash pile
sig = [[0.1, 0], [0, 0.1]] # spread of pile
var = 0.1 # error in measurements
field = np.zeros((m,m))# array of trash pieces dispersed on field
visits = np.zeros((m,m))# array to track number of visits to each gridpoint
reward = np.zeros((m,m))# array of expected means of each gridpoint
T = n # number of time steps
delta = 1 # amount reward decreases per visit

# place trash in field
trash = np.random.multivariate_normal(mu, sig, n)
for i in range(n):
    x = int(trash[i][0])
    y = int(trash[i][1])
    field[x][y] += 1
    
print(field)

[[ 0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 0. 29. 24.  1.  0.]
 [ 0. 20. 25.  0.  0.]
 [ 0.  0.  0.  0.  0.]]


In [40]:
# intialize agent
for i in range(m):
    for j in range(m):
        visits[i][j] += 1
        measure = field[i][j]
        reward[i][j] = round(np.random.normal(measure, var),1)
print(visits)
print(reward)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[-0.1 -0.1  0.1  0.1  0. ]
 [ 0.1  1.2 -0.1 -0.1 -0.1]
 [ 0.1 29.  24.1  1.2  0. ]
 [-0.1 20.  24.8  0.1  0.1]
 [ 0.1 -0.2 -0.   0.1 -0.1]]


In [41]:
# for T time steps choose an arm to visit and get a reward
for i in range (1,T+1):
    print("Time step: ", i)
    expected_mean = np.divide(reward, visits)
    Q = expected_mean + np.divide(math.sqrt(2*math.log(i)),np.sqrt(visits))
    ind = np.unravel_index(np.argmax(Q), Q.shape)
    measure = round(np.random.normal(field[ind], var),1)
    #reward[ind] += (measure - delta*visits[ind])
    reward[ind] += measure
    field[ind] -= 1
    visits[ind] += 1
    print(Q)
    print(ind)
    print(visits)

Time step:  1
[[-0.1 -0.1  0.1  0.1  0. ]
 [ 0.1  1.2 -0.1 -0.1 -0.1]
 [ 0.1 29.  24.1  1.2  0. ]
 [-0.1 20.  24.8  0.1  0.1]
 [ 0.1 -0.2  0.   0.1 -0.1]]
(2, 1)
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 2. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Time step:  2
[[ 1.07741002  1.07741002  1.27741002  1.27741002  1.17741002]
 [ 1.27741002  2.37741002  1.07741002  1.07741002  1.07741002]
 [ 1.27741002 29.33255461 25.27741002  2.37741002  1.17741002]
 [ 1.07741002 21.17741002 25.97741002  1.27741002  1.27741002]
 [ 1.27741002  0.97741002  1.17741002  1.27741002  1.07741002]]
(2, 1)
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 3. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Time step:  3
[[ 1.38230381  1.38230381  1.58230381  1.58230381  1.48230381]
 [ 1.58230381  2.68230381  1.38230381  1.38230381  1.38230381]
 [ 1.58230381 28.8558085  25.58230381  2.68230381  1.48230381]
 [ 1.38230381 21.48230381 26.28230381  1.58230381  1.58230381]
 [ 1.58230381  1.28230381  1.48230381  1.58230381  1.

In [42]:
visits -=1
print(visits)
#print(field - visits)
print(field)

[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0. 34. 24.  0.  0.]
 [ 0. 16. 26.  0.  0.]
 [ 0.  0.  0.  0.  0.]]
[[ 0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 0. -5.  0.  1.  0.]
 [ 0.  4. -1.  0.  0.]
 [ 0.  0.  0.  0.  0.]]
